name: skt_sikring
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3
  slide_to_act: ^2.0.2
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar: ^6.2.1
  badges: ^3.1.2
  flutter_rating: ^2.0.2
  image_picker:
  get_storage: ^2.1.1
  table_calendar: ^3.2.0
  signature: ^6.0.0
  carousel_slider: ^5.1.1
  video_player: ^2.10.0
  dropdown_button2: ^2.3.9
  dotted_border: ^3.0.1
  flutter_vlc_player: ^7.4.3
  flutter_secure_storage: ^9.2.4
  mime_type: ^1.0.1
  http: ^1.4.0
  gif: ^2.3.0
  connectivity_plus: ^6.1.4
  path_provider: any
  flutter_image_compress: ^2.4.0
  socket_io_client: ^3.1.2
  flutter_phoenix:
  html: ^0.15.6



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/logo/
    - assets/language/
