export 'package:skt_sikring/presentation/customSuccessMassege/custom_success_massege.screen.dart';
export 'package:skt_sikring/presentation/forgetPassword/forget_password.screen.dart';
export 'package:skt_sikring/presentation/home/home.screen.dart';
export 'package:skt_sikring/presentation/logIn/log_in.screen.dart';
export 'package:skt_sikring/presentation/otpPage/otp_page.screen.dart';
export 'package:skt_sikring/presentation/resetPassword/reset_password.screen.dart';
export 'package:skt_sikring/presentation/signUpPage/sign_up_page.screen.dart';
export 'package:skt_sikring/presentation/splashLanguage/splash_language.screen.dart';
export 'package:skt_sikring/presentation/splashScreen/splash_screen.screen.dart';